development:
  adapter: postgresql
  database: bowtie_beer_development
  host: localhost
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: bowtie_beer_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bowtie_beer_production
  pool: 5
  timeout: 5000
